### ISSUE TITLE
@GaussianProcess/construct.m line 86

### ISSUE THREAD

**Issue by unoe** [MathRocks/MathRocks#1]
It would be better to avoid using inv(.) in Matlab due to numerical instabilities.
http://blogs.mathworks.com/loren/2007/05/16/purpose-of-inv/

A better implementation would be using the cholesky of the (K + sigma2 * I) and solving two linear systems.
C = K + sigma2 * I;
n = size(C,1);
R = chol(C);
invK = R \ (R' \ eye(n));

Otherwise something like
invK = (K + sigma1 * I) \ eye(n)
will work too.

**Comment by IvanUkhov** [comment]
Thank you for the issue! The article you link to starts with the following premise:

> In practice, it is seldom necessary to form the explicit inverse of a matrix.

In the current logic of `GaussianProcess`, the explicit inverse is needed. I suppose the code that you propose is applicable to a generic square matrix. Then, if it’s strictly better than what `inv` is currently doing, why doesn’t it reside inside `inv`? My guess is that there is no difference between `inv(A)` and `A \ eye(size(A, 1))`.

**Comment by unoe** [comment]
Happy to contribute, Ivan! I also wanted to say that I love fonts :-)

I understand that the explicit inverse is needed for GPs, and you can calculate it with both options of code I wrote above.
The code provided by Rasmussen calculates it using the Cholesky decomposition as I wrote you above. The Cholesky factor is a fundamental tool in GPs.

To test the efficiency of backslash vs inv, try this simple example yourself:
```
M = gallery ('frank', 16) ;
x0 = ones (16,1);
b = M*x0 ;

x = inv(M)*b;
norm (b-M*x)
x = M\b;
norm (b-M*x)
```

Compare the norm of the residuals. Which one is more accurate?
And this is just a very small matrix. Imagine a huge one!
The reason why Mathworks doesn't implement `inv` like that is not very clear. But what is clear is that in all documentation they suggest you to use backslash instead!

**Comment by unoe** [comment]
Follow up, I just tried this:
```
M = gallery ('frank', 16) ;
x0 = ones (16,1);
b = M*x0 ;

invM = M\eye(size(M,1));
x = inv(M)*b;
norm (b-M*x)
x = invM*b;
norm (b-M*x)
```
and the norms of the residuals are very similar! That's very interesting Ivan... Well spotted!

**Comment by IvanUkhov** [comment]
Thanks for the examples! The conclusion is that the backslash operator is certainly the way to go when solving system of linear equations, but it doesn’t seem to help much when it’s given this sort of artificial right-hand side.

**Comment by unoe** [comment]
Another option I was considering that might speed up things, is to solve triangular systems only and store the Cholesky factor, alpha and v instead of the inverse K.
`L = chol(K);`
`alpha = L\(L'\(y-m))` and `v = L\k`.
Then the predictive mean is `k'*alpha` and the variance is `kss - v'*v`.

Other options are discussed in the paper by Radford Neal, but not sure they would make much of a difference in term of efficiency. He also talks about the log marginal likelihood.
http://www.cs.toronto.edu/~radford/ftp/val6gp.pdf

Do you think it would make a big difference in terms of computational time?

**Comment by IvanUkhov** [comment]
Performance is dangerous to speculate about without having actual measurements. In such cases, I try to make sure first that the bottleneck is exactly where I think it is. I do so by running MATLAB’s [profiler](https://se.mathworks.com/help/matlab/matlab_prog/profiling-for-improving-performance.html); it has a great GUI, and it allows you to find out how much time is spent on each line of your and their code. Once I’m positive about the location of the bottleneck, I start to make adjustments to the corresponding code while monitoring how these adjustments are reflected in the profiler.

If you find a way to substantially improve the performance and/or stability of `GaussianProcess` and are able to demonstrate this, I’ll be more than happy to accept a pull request from you! Thanks!
